### ISSUE TITLE
Per-method controller for routes

### ISSUE THREAD

**Issue by anlutro** [autarky/framework#47]
Best illustrated with an example

``` yml
example.route:
  path: '/foo/bar/{id:[0-9]+}'
  methods:
    get: [ExampleController, showAction]
    post: [ExampleController, updateAction]
    delete: [ExampleController, deleteAction]
```

```
+---------------+---------+----------------------+----------------------------------+
| Name          | Methods | Path                 | Controller                       |
+---------------+---------+----------------------+----------------------------------+
| first.route   | GET     | /                    | ExampleController::exampleAction |
| second.route  | GET     | /bar/{foo}           | ExampleController::otherAction   |
| example.route | GET     | /foo/bar/{id:[0-9]+} | ExampleController::showAction    |
|               | POST    | /foo/bar/{id:[0-9]+} | ExampleController::updateAction  |
|               | DELETE  | /foo/bar/{id:[0-9]+} | ExampleController::deleteAction  |
+---------------+---------+----------------------+----------------------------------+
```

Questions:
- One instance of Route containing all controllers or multiple instances?
- What if different filters should be applied to each HTTP method?
