### ISSUE TITLE
Multiple logging channels

### ISSUE THREAD

**Issue by anlutro** [autarky/framework#49]
Add a config file named logging.yml, syntax very similar to that of Symfony 2.

```yml
channels:
  default:
    handlers: [main, syslog]

handlers:
  main:
    type: fingers_crossed
    level: warning
    handler: debuglog
  errlog:
    type: stream
    path: /var/log/my_application.error.log
    level: error
  debuglog:
    type: stream
    path: /var/log/my_application.debug.log
    level: debug
  syslog:
    type: syslog
    level: error
```

When injecting a logger into your classes, you don't want to type-hint the class that contains all the different logging channels, you just want to type-hint Psr\Log\LoggerInterface. Need to come up with a way to easily tell the container what channel you want without having to re-define the entire class factory - see #50
